//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleData.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleData.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Intel Core i9-9900KS
        ///Intel Core i9-10980XE
        ///Intel Core i7-9700K
        ///Intel Core i9-9900K
        ///Intel Core i9-9900KF
        ///Intel Xeon W-3175X
        ///AMD Threadripper 3970X
        ///AMD Threadripper 3960X
        ///AMD Threadripper 3990X
        ///AMD Ryzen 9 3900X
        ///AMD Ryzen 9 3950X
        ///Intel Core i9-9980XE
        ///AMD Ryzen 9 3900
        ///AMD Ryzen 7 3700X
        ///AMD Ryzen 7 3800X
        ///Intel Core i7-8700K
        ///Intel Core i7-8700
        ///Intel Core i9-7960X
        ///AMD Ryzen 5 3600X
        ///Intel Core i5-9600K
        ///AMD Ryzen 5 3600
        ///Intel Core i5-8600K
        ///AMD Ryzen 7 2700X ähnelt.
        /// </summary>
        internal static string cpu {
            get {
                return ResourceManager.GetString("cpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aaren
        ///Aarika
        ///Abagael
        ///Abagail
        ///Abbe
        ///Abbey
        ///Abbi
        ///Abbie
        ///Abby
        ///Abbye
        ///Abigael
        ///Abigail
        ///Abigale
        ///Abra
        ///Ada
        ///Adah
        ///Adaline
        ///Adan
        ///Adara
        ///Adda
        ///Addi
        ///Addia
        ///Addie
        ///Addy
        ///Adel
        ///Adela
        ///Adelaida
        ///Adelaide
        ///Adele
        ///Adelheid
        ///Adelice
        ///Adelina
        ///Adelind
        ///Adeline
        ///Adella
        ///Adelle
        ///Adena
        ///Adey
        ///Adi
        ///Adiana
        ///Adina
        ///Adora
        ///Adore
        ///Adoree
        ///Adorne
        ///Adrea
        ///Adria
        ///Adriaens
        ///Adrian
        ///Adriana
        ///Adriane
        ///Adrianna
        ///Adrianne
        ///Adriena
        ///Adrienne
        ///Aeriel
        ///Aeriela
        ///Aeriell
        ///Afton
        ///Ag
        ///Agace
        ///Agata
        ///Agatha
        ///Agathe
        ///Aggi
        ///Aggie
        ///Aggy
        ///Ag [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string firstnames {
            get {
                return ResourceManager.GetString("firstnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nvidia Titan RTX
        ///Nvidia GeForce RTX 2080 Ti
        ///Nvidia GeForce RTX 2080 Super
        ///Nvidia GeForce RTX 2080
        ///Nvidia GeForce RTX 2070 Super
        ///Nvidia Titan X
        ///Nvidia GeForce GTX 1080 Ti
        ///AMD Radeon VII
        ///AMD Radeon RX 5700 XT
        ///Nvidia GeForce RTX 2070
        ///Nvidia GeForce RTX 2060 Super
        ///AMD Radeon RX 5700
        ///Nvidia GeForce GTX 1080
        ///AMD Radeon RX 5600 XT
        ///AMD Radeon RX Vega 64
        ///Nvidia GeForce RTX 2060
        ///AMD Radeon RX Vega 56
        ///Nvidia GeForce GTX 1070 Ti
        ///Nvidia GeForce GTX 1660 Ti
        ///Nvidia GeForce GTX 1070
        ///Nvidia GeForce GTX 1 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string gpu {
            get {
                return ResourceManager.GetString("gpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aaberg
        ///Aalst
        ///Aara
        ///Aaren
        ///Aarika
        ///Aaron
        ///Aaronson
        ///Ab
        ///Aba
        ///Abad
        ///Abagael
        ///Abagail
        ///Abana
        ///Abate
        ///Abba
        ///Abbate
        ///Abbe
        ///Abbey
        ///Abbi
        ///Abbie
        ///Abbot
        ///Abbotsen
        ///Abbotson
        ///Abbotsun
        ///Abbott
        ///Abbottson
        ///Abby
        ///Abbye
        ///Abdel
        ///Abdella
        ///Abdu
        ///Abdul
        ///Abdulla
        ///Abe
        ///Abebi
        ///Abel
        ///Abelard
        ///Abell
        ///Abercromby
        ///Abernathy
        ///Abernon
        ///Abert
        ///Abeu
        ///Abey
        ///Abie
        ///Abigael
        ///Abigail
        ///Abigale
        ///Abijah
        ///Abisha
        ///Abisia
        ///Abixah
        ///Abner
        ///Aborn
        ///Abott
        ///Abra
        ///Abraham
        ///Abrahams
        ///Abrahamsen
        ///Abrahan
        ///Abram
        ///Abramo
        ///Abrams
        ///Abramson
        ///Abran
        ///Abroms
        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string lastnames {
            get {
                return ResourceManager.GetString("lastnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gigabyte Z390 Aorus Pro Wifi
        ///Asus ROG Maximus XI Code Z390 Gaming
        ///Gigabyte Z390 UD
        ///MSI MPG Z390M Gaming Edge AC
        ///Asus ROG Strix Z390-I Gaming
        ///X470 Aorus Gaming 7 Wi-Fi
        ///MSI X470 Gaming Plus
        ///ASRock B450M-HDV
        ///ASUS ROG Strix X470-I
        ///ASRock X299 Taichi
        ///ASRock X399 Professional Gaming sTR4 ähnelt.
        /// </summary>
        internal static string mainboard {
            get {
                return ResourceManager.GetString("mainboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1.0
        ///1.1
        ///2.0
        ///3.0
        ///3.5
        ///4.0
        ///4.5
        ///4.5.1
        ///4.5.2
        ///4.6
        ///4.6.1
        ///4.6.2
        ///4.7
        ///4.7.1 ähnelt.
        /// </summary>
        internal static string netframework {
            get {
                return ResourceManager.GetString("netframework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version 1507
        ///Version 1511
        ///Version 1607
        ///Version 1703
        ///Version 1709
        ///Version 1803
        ///Version 1809
        ///Version 1903
        ///Version 1909
        ///Version 2004 ähnelt.
        /// </summary>
        internal static string patchlevel {
            get {
                return ResourceManager.GetString("patchlevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Corsair Vengeance LED
        ///G.Skill Trident Z RGB
        ///Kingston HyperX Predator
        ///Kingston HyperX Fury
        ///Corsair Dominator Platinum RGB
        ///HyperX Fury RGB 3733MHz
        ///G.Skill Trident Z RGB DC
        ///Adata Spectrix D80
        ///G.Skill TridentZ Royal
        ///Corsair Vengeance LPX
        ///G.Skill Mac RAM
        ///Crucial Ballistix Sport ähnelt.
        /// </summary>
        internal static string ram {
            get {
                return ResourceManager.GetString("ram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Windows 1.0
        ///Windows 2.x
        ///Windows 3.0
        ///Windows 3.1
        ///Windows 95
        ///Windows 98
        ///Windows 2000
        ///Windows XP
        ///Windows XP Prof. x64
        ///Windows Vista
        ///Windows 7
        ///Windows 8
        ///Windows 10 ähnelt.
        /// </summary>
        internal static string windows {
            get {
                return ResourceManager.GetString("windows", resourceCulture);
            }
        }
    }
}
